openapi: 3.0.3
info:
  version: 1.0.0
  title: SeichiRankingBFF API
  description: SeichiRankingBFFが提供する、ランキング取得に関するAPI。

servers:
  - url: https://bff.ranking.seichi.click

paths:
  /ranking:
    get:
      description: ページネートされたランキングを取得する
      parameters:
        - $ref: "#/components/parameters/ranking_limit"
        - $ref: "#/components/parameters/ranking_offset"
        - $ref: "#/components/parameters/ranking_type"
        - $ref: "#/components/parameters/time_range"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlayerRankingRecord"

  /player-ranks/{uuid}:
    get:
      description: UUIDで指定される特定のプレーヤーのランキング順位を取得する
      parameters:
        - $ref: "#/components/parameters/player_uuid"
        - $ref: "#/components/parameters/ranking_type"
        - $ref: "#/components/parameters/time_range"
      responses:
        "200":
          description: Successful response
          # TODO:

components:
  parameters:
    time_range:
      name: time_range
      in: query
      description: ランキングの集計を行う期間を指定する文字列
      schema:
        $ref: "#/components/schemas/AggregationTimeRange"

    ranking_type:
      name: type
      in: query
      description: ランキングの集計に使う統計情報を指定する文字列
      schema:
        $ref: "#/components/schemas/AggregationParameterType"

    ranking_limit:
      name: limit
      in: query
      description: 返されるランキングの最大レコード数
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 1000

    ranking_offset:
      name: offset
      in: query
      description: 返されるランキングのオフセット
      schema:
        type: integer
        format: int32
        minimum: 0

    player_uuid:
      name: uuid
      in: path
      description: プレーヤーのUUID
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    AggregationTimeRange:
      type: string
      description: ランキングの集計を行う期間を指定する文字列
      default: all
      enum:
        - all
        - year
        - month
        - week
        - day

    AggregationParameterType:
      type: string
      description: ランキングの集計に使う統計情報を指定する文字列
      default: break
      enum:
        - break
        - build
        - play_ticks
        - vote_count

    Player:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
        last_login:
          type: string
          format: date-time

    PlayerRankingRecord:
      type: object
      properties:
        player:
          $ref: "#/components/schemas/Player"
        rank_position:
          type: integer
          format: int32
          minimum: 1
        value:
          type: integer
          format: int64
